### ISSUE TITLE
Writing documentation 

### ISSUE THREAD

**Issue by Tresor-Kasenda** [unify-ui-dev/flexilla#36]
It's can helps us to know how to use this package and give us more examples

Content

- [x] Init documentation
- [x] single component page
- [x] Build Home page
- [x] Showcases

Getting Started
- [x] Introduction
- [x] Framework guide

Components
- [x] Accordion
- [x] auto resize area
- [x] collapse
- [x] custom range- [x] dismissible
- [x] dropdown
- [x] modal
- [x] offcanvas
- [x] popper
- [x] tabs
- [x] tooltip/popover

**Comment by unifyui** [comment]
Content

Getting Started
- [ ] Introduction
- [ ] Framework guide

Components
- [ ] Accordion
- [ ] auto resize area
- [ ] collapse
- [ ] custom range
- [ ] dark mode
- [ ] dismissible
- [ ] dropdown
- [ ] modal
- [ ] offcanvas
- [ ] popper
- [ ] tabs
- [ ] tooltip/popover
