### ISSUE TITLE
Typo in the contributing file 

### ISSUE THREAD

**Issue by hemangtk** [unify-ui-dev/flexilla#87]
Typo in th contributing file under the have a question 
-"Go to the Discor Server" it should be Go to the Discord Server

**Comment by hemangtk** [comment]
hey @Johnkat-Mj 
i know i have my task assigned but this seems a easier and a quicker task to do 
can you just assign me this too, so that i fix it in a minute and then continue working on the other task?

**Comment by Johnkat-Mj** [comment]
Hey @hemangtk you can fix it

**Comment by hemangtk** [comment]
Hey @Johnkat-Mj just have a look 
i fixed it let me know if there are any changes required
