### ISSUE TITLE
Adding functionality on hover over the buttons

### ISSUE THREAD

**Issue by Athaxv** [unify-ui-dev/flexilla#89]
On the hero section buttons there is nothing happening on hovering over them
![Screenshot 2024-10-10 213150](https://github.com/user-attachments/assets/2814ec39-fff1-4e51-a7ed-d87d36ab6de7)
I want to add a functionality on hovering over these button to improve the functionality of the homepage

**Comment by Athaxv** [comment]
please assign it to me and can you add hacktoberfest label over it also

**Comment by Johnkat-Mj** [comment]
Okay, @Athaxv you can work on it

**Comment by Johnkat-Mj** [comment]
Hey @Athaxv 

Thank you for taking the time to look into ways to improve the homepage! After considering it more carefully, I realized that while adding hover functionality can enhance the visual experience, it may not provide a substantial learning opportunity or impactful improvement, which is really the goal here, especially during Hacktoberfest.

This event is a chance for contributors to engage with features that help them learn and grow in meaningful ways. I’d like to encourage contributions that involve a bit more in terms of functionality, usability, or accessibility. If you have any ideas for such improvements, feel free to share... I’d be happy to discuss them with you!

For now, I’ll remove the Hacktoberfest label on this one, but I’d love to explore more substantial contributions with you. Thanks again for your interest, and I look forward to any other ideas you might have!
