### ISSUE TITLE
Modify component 

### ISSUE THREAD

**Issue by anisha-singhal** [unify-ui-dev/flexilla#90]
I want to add hover effect and add icons in the community. Please assign me this under the label of hacktober.
![Screenshot 2024-10-10 232503](https://github.com/user-attachments/assets/9f41a733-a948-4d1d-93dd-07ab2e1bd21f)

**Comment by Johnkat-Mj** [comment]
Hey @anisha-singhal 

Thanks for your interest! While adding hover effects and icons can enhance the visual appeal, it’s important for Hacktoberfest contributions to focus on impactful improvements that help users and enhance functionality. Visual changes alone might not fully align with that goal.

If you have ideas for meaningful functionality updates or enhancements ..., feel free to share! We’d love to focus on contributions that offer more substantial value to the project.

Thanks again, and happy coding!
